version: '3.8'

services:
    test_nginx:
        container_name: test_nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ../www:/var/www
            - ../logs/nginx:/var/log/nginx
        links:
            - test_php
        networks:
            test_net:
                ipv4_address: 172.28.0.2

    test_php:
        build: php
        container_name: test_php
        links:
            - test_sql
        volumes:
            - ../www:/var/www
            - ../logs/php/access.log:/var/log/access.log
            - ../logs/php/error.log:/var/log/error.log
            - ./php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
        networks:
            test_net:
                ipv4_address: 172.28.0.3

    test_sql:
        image: mariadb:latest
        container_name: test_sql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: eshop
        ports:
            - "3306:3306"
        volumes:
            - ../mysql:/var/lib/mysql
        networks:
            test_net:
                ipv4_address: 172.28.0.4

    test_myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: test_myadmin
        links: 
            - test_sql:db
        ports:
            - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        depends_on:
            - test_sql
        networks:
            test_net:
                ipv4_address: 172.28.0.5

networks:
    test_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
